# wengwengweng

[package]
name = "packapp"
version = "0.0.1"
authors = ["t <voygagaga@outlook.com>"]
edition = "2018"
description = "pack a binary to MacOS .app bundle"
license = "Zlib"

[dependencies]
clap = "^2"
plist = "^0"
serde_derive = "^1"
serde = "^1"

