# wengwengweng

[package]
name        = "packapp"
description = "pack a binary to MacOS .app bundle"
version     = "0.1.1"
authors     = ["t <voygagaga@outlook.com>"]
edition     = "2018"
license     = "Zlib"
repository  = "https://github.com/slmjkdbtl/packapp/"
readme      = "README.md"

[dependencies]
clap         = "~2.32"
plist        = "~0.3"

[dependencies.serde]
version  = "~1.0"
features = ["derive"]

