# wengwengweng

[package]
name        = "packapp"
description = "pack a binary to MacOS .app bundle"
version     = "0.0.5"
authors     = ["t <voygagaga@outlook.com>"]
edition     = "2018"
license     = "Zlib"
repository  = "https://github.com/slmjkdbtl/packapp/"
readme      = "README.md"

[dependencies]
clap         = "^2"
plist        = "^0"
serde_derive = "^1"
serde        = "^1"

